### ISSUE TITLE
Which OSS license governs this CSS file?

### ISSUE THREAD

**Issue by waingold** [nicolashery/markdownpad-github#11]

**Comment by nicolashery** [comment]
I'm guessing the MIT license will be fine for this...

@evanwon Just checking, are you still using this for MarkdownPad, or do you have your own version of it? In either case, see any reason why we couldn't add MIT license to it? Thanks!

On a side node @waingold, some of the styles might be slightly outdated as I haven't checked on this in a while, and I'm sure GitHub has tweaked a few things since then. The general look should still be the same though...

You might also be interested in this: https://github.com/atom/markdown-preview/blob/master/stylesheets/markdown-preview.less It's from the [Atom](https://atom.io/) editor.

**Comment by evanwon** [comment]
@nicolashery Yes, this is still the default stylesheet for MarkdownPad. When this is updated, I also update MarkdownPad's version.

**Comment by nicolashery** [comment]
Thanks @evanwon. I think there are a few small details that are outdated, I'll try and update them sometime.

@waingold License added in https://github.com/nicolashery/markdownpad-github/commit/90907b76b8bada7131332728326a6d7bca45bbb5

**Comment by evanwon** [comment]
@nicolashery Great! Just send me a message or email.

**Comment by evanwon** [comment]
@nicolashery (and thanks as always :smile:)

**Comment by waingold** [comment]
Thank you!
