### ISSUE TITLE
Too big images

### ISSUE THREAD

**Issue by malleor** [nicolashery/markdownpad-github#7]
The `max-width` of inserted images is not being applied since apparently `markdown-body` class is not introduced. Changing `.markdown-body` to `body` naturally fixes the issue. Interested in a Pull Request for this 10-char fix? ;)

**Comment by nicolashery** [comment]
Hey @malleor thanks a lot for catching that! I'm surprised it slipped through and went on unnoticed (we must not be using a lot of images in our Markdown haha)..

Anyway, fixed in https://github.com/nicolahery/markdownpad-github/commit/29d1c5bc36da364ad5aa86946d420b7bbc54a253

@evanwon you might want to include this in MardownPad's next update?

**Comment by evanwon** [comment]
@nicolahery Definitely, I'll make sure this gets included with the next release. Thanks for catching this @malleor!

**Comment by malleor** [comment]
You're welcome, guys. Thank _you_ for MarkdownPad ;)
